# Package - Updates Available
# List all available updates of entities with device class update
#
# You must set in secrets.yaml
# notify_service_updates: "notify.notify"
# delay_notify_updates: "24:00:00"
#
# If you want to exlcude entities create group ignored_updates in groups.yaml
#
# Example:
# ignored_updates:
#   entities:
#     - binary_sensor.updater

script:
  # Script to update this package from GitHub
  update_packages:
    sequence:
      - service: downloader.download_file
        data:
          overwrite: true
          url: >-
            https://raw.githubusercontent.com/topaniot/HomeAssistant_Packages/main/packages/updates_available.yaml

group:
  ignored_updates:
    name: "|| Ignored Updates"
    entities: []

  turn_off_automations:
    entities:
      - automation.updates_available

template:
  - trigger:
      - platform: time_pattern
        seconds: "/1"
    sensor:
      - name: "|| Updates Available"
        icon: "hass:update"
        state: >
              {% set result = namespace(updates=[]) %}
              {% for state in states.update | selectattr('state', '==', 'on')
                |rejectattr('entity_id','in',state_attr('group.ignored_updates','entity_id')) %}
                {% if state.state == 'on'  %}
                  {% set result.updates = result.updates + [state.name 
                    ~ ' (' ~ state.attributes.installed_version ~ ' -> ' 
                    ~ state.attributes.latest_version ~ ')'] %}
                {% endif %}
              {% endfor %}
              {{ result.updates|count }}
        attributes:
            names: >
              {% set result = namespace(updates=[]) %}
              {% for state in states.update | selectattr('state', '==', 'on')
                |rejectattr('entity_id','in',state_attr('group.ignored_updates','entity_id')) %}
                {% if state.state == 'on'  %}
                  {% set result.updates = result.updates + [state.name 
                    ~ ' (' ~ state.attributes.installed_version ~ ' -> ' 
                    ~ state.attributes.latest_version ~ ')'] %}
                {% endif %}
              {% endfor %}
              {{ result.updates|join (', ') }}
      - name: "|| Updates in Progress"
        icon: "hass:update"
        state: >
              {{ states.update
                |selectattr('attributes.in_progress','defined')
                |selectattr('attributes.in_progress','true')
                |list|count
              }}
        attributes:
            names: >
              {{ states.update
                |selectattr('attributes.in_progress','defined')
                |selectattr('attributes.in_progress','true')
                |map(attribute='name')|join (", ")
              }}

input_boolean:
  update_available_alert:
    name: "|| Update Available Alert"
    icon: "hass:alert-circle"

automation:
  # Notify when updates are available
  - id: "updates_available"
    alias: "|| Updates Available"
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.updates_available
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.updates_available
                state: unknown
            sequence: []
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                above: '0'
                below: '2'
            sequence:
              - delay: !secret delay_notify_updates
              - service: !secret notify_service_updates
                data:
                  message: |
                    ⚙️ Este o actualizare disponibilă:
                    – {{ state_attr('sensor.updates_available','names').split(',') | join('
                    –') }}
                  data:
                    disable_notification: True
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.update_available_alert
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                above: '1'
            sequence:
              - delay: !secret delay_notify_updates
              - service: !secret notify_service_updates
                data:
                  message: |
                    ⚙️ Sunt {{ states('sensor.updates_available')|int }} actualizări disponibile:
                    – {{ state_attr('sensor.updates_available','names').split(',') | join('
                    –') }}
                  data:
                    disable_notification: True
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.update_available_alert
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                below: '1'
              - condition: state
                entity_id: input_boolean.update_available_alert
                state: 'on'
            sequence:
              - service: !secret notify_service_updates
                data:
                  message: "🎉 Dispozitivele și serviciile sunt actualizate!"
                  data:
                    disable_notification: True
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.update_available_alert
        default: []


  # Notify when updates are in progress
  - id: "updates_in_progress"
    alias: "|| Updates in Progress"
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.updates_in_progress
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.updates_in_progress
                state: unknown
            sequence: []
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_in_progress
                above: '0'
                below: '2'
            sequence:
              - service: !secret notify_service_updates
                data:
                  message: |
                    ⚙️ Este o actualizare în progress:
                    – {{ state_attr('sensor.updates_in_progress','names').split(',') | join('
                    –') }}
                  data:
                    disable_notification: True
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.update_available_alert
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_in_progress
                above: '1'
            sequence:
              - service: !secret notify_service_updates
                data:
                  message: |
                    ⚙️ Sunt {{ states('sensor.updates_in_progress')|int }} actualizări în progress:
                    – {{ state_attr('sensor.updates_in_progress','names').split(',') | join('
                    –') }}
                  data:
                    disable_notification: True
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.update_available_alert
        default: []